// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi2jR3BZEVEYQggBH1bGpx6oQ1dvnZxh8',
    appId: '1:859932569709:web:16969674e762d640bc0f64',
    messagingSenderId: '859932569709',
    projectId: 'whatsapp-clone-e36d4',
    authDomain: 'whatsapp-clone-e36d4.firebaseapp.com',
    storageBucket: 'whatsapp-clone-e36d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQYMdeZfekNhn9OWb28Tu99JTOb6iiPxQ',
    appId: '1:859932569709:android:e51c3c39d53afbc9bc0f64',
    messagingSenderId: '859932569709',
    projectId: 'whatsapp-clone-e36d4',
    storageBucket: 'whatsapp-clone-e36d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjQk4IO2X4UQasEH3vUQ11Wm8N_DKor5E',
    appId: '1:859932569709:ios:2b7503908055a4c5bc0f64',
    messagingSenderId: '859932569709',
    projectId: 'whatsapp-clone-e36d4',
    storageBucket: 'whatsapp-clone-e36d4.appspot.com',
    iosClientId: '859932569709-rn62vqjrt3dc1q0mu28jk1bbt62i5vha.apps.googleusercontent.com',
    iosBundleId: 'com.flutterthailand.whatsappclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjQk4IO2X4UQasEH3vUQ11Wm8N_DKor5E',
    appId: '1:859932569709:ios:2b7503908055a4c5bc0f64',
    messagingSenderId: '859932569709',
    projectId: 'whatsapp-clone-e36d4',
    storageBucket: 'whatsapp-clone-e36d4.appspot.com',
    iosClientId: '859932569709-rn62vqjrt3dc1q0mu28jk1bbt62i5vha.apps.googleusercontent.com',
    iosBundleId: 'com.flutterthailand.whatsappclone',
  );
}
